version: '3.8'

services:
  # Web server configuration (PHP + Apache)
  web:
    build: .                  # Build from Dockerfile
    ports:
      - "8000:80"             # Access web via 8000 localhost
    volumes:
      - ./src:/var/www/html   # Sync code from src/ into container
    depends_on:
      - db                    # Request lauching database first

  # Database configuration (MySQL)
  db:
    image: mysql:8.0          # Use image MySQL version 8.0
    ports:
      - "3306:3306"           # Open 3306 to let external software connect (DBeaver, etc)
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}     # Root account password
      MYSQL_DATABASE: ${MYSQL_DATABASE}               # Automatically generate database
      MYSQL_USER: ${MYSQL_USER}                       # Automatically generate user account
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}               # User account password
    volumes:
      - db_data:/var/lib/mysql          # DB data will not be lost when turn off Docker

volumes:
  db_data: