<?php

// Load language from session or default to English
if (!isset($_SESSION['lang'])) {
    $_SESSION['lang'] = 'en';
}

// Change language via GET param
if (isset($_GET['lang']) && in_array($_GET['lang'], ['en', 'vi'])) {
    $_SESSION['lang'] = $_GET['lang'];
}

$lang = $_SESSION['lang'];

$langData = [
    'en' => [
        // Navbar
        'nav_home'         => 'HOME',
        'nav_features'     => 'FEATURES',
        'nav_plans'        => 'VPS PLANS',
        'nav_docs'         => 'DOCS',
        'nav_blog'         => 'BLOG',
        'nav_login'        => 'Login',
        'nav_register'     => 'Start now',
        'nav_inbox'        => 'Inbox',
        'nav_profile'      => 'My Profile',
        'nav_orders'       => 'My Orders',
        'nav_logout'       => 'Logout',
        'nav_cart'         => 'Cart',
        'nav_admin'        => 'Admin',

        // Hero
        'hero_title1'      => 'Cloud VPS that makes your',
        'hero_title2'      => 'FASTER!',
        'hero_sub'         => 'Astral Cloud provides high-performance VPS, fast deployment, stable security, and easy management for students, developers, and businesses.',
        'hero_btn_plans'   => 'View VPS Plans',
        'hero_btn_start'   => 'Get Started',

        // About
        'about_title'      => 'Why Astral Cloud?',
        'about_desc'       => 'We simulate a modern VPS rental and management system, helping users find server packages, place orders, make demo payments, and track activation status.',
        'about_uptime'     => 'Uptime',
        'about_uptime_desc'=> 'Always-on infrastructure for stable VPS performance.',
        'about_storage'    => 'SSD Storage',
        'about_storage_desc'=>'Ultra-fast storage for websites, APIs and applications.',
        'about_support'    => 'Support',
        'about_support_desc'=>'Professional assistance whenever you need help.',
        'about_ddos'       => 'Protection',
        'about_ddos_desc'  => 'Advanced protection against malicious attacks.',

        // Plans page
        'plans_title'      => 'Our VPS Packages',
        'plans_sub'        => 'Popular VPS packages for a variety of usage needs.',
        'plans_all_title'  => 'All VPS Plans',
        'plans_all_sub'    => 'Choose the VPS package that suits your needs.',
        'plans_search'     => 'Search plans...',
        'plans_sort_price_asc'=> 'Price: Low → High',
        'plans_sort_price_desc'=>'Price: High → Low',
        'plans_sort_rating'=> 'Highest Rated',
        'plans_sort_name'  => 'Name: A → Z',
        'plans_search_btn' => 'Search',
        'plans_clear'      => 'Clear',
        'plans_no_results' => 'No VPS plans match your search.',
        'plans_results_for'=> 'Results for',
        'plans_found'      => 'product(s) found',
        'plans_month'      => '/month',
        'plans_reviews'    => 'Reviews',
        'plans_no_reviews' => 'No reviews',
        'plans_add_cart'   => 'Add to Cart',
        'plans_out_of_stock'=>'Out of Stock',
        'plans_view'       => 'View plan',
        'plans_cpu'        => 'CPU',
        'plans_ram'        => 'RAM',
        'plans_storage'    => 'Storage',
        'plans_bandwidth'  => 'Bandwidth',

        // Auth
        'login_title'      => 'Log in | Astral Cloud',
        'login_heading'    => 'Login',
        'login_email'      => 'Email',
        'login_password'   => 'Password',
        'login_btn'        => 'Log In',
        'login_no_account' => "Don't have an account?",
        'login_forgot'     => 'Forgot password?',
        'login_register'   => 'Register',

        'register_title'   => 'Registration | Astral Cloud',
        'register_heading' => 'Create Account',
        'register_name'    => 'Full Name',
        'register_phone'   => 'Phone (optional)',
        'register_confirm' => 'Confirm Password',
        'register_btn'     => 'Create Account',
        'register_have_account' => 'Already have an account?',

        'mfa_title'        => 'MFA Verification | Astral Cloud',
        'mfa_heading'      => 'Two-Factor Authentication',
        'mfa_sub'          => 'Enter the 6-digit code from your authenticator app.',
        'mfa_btn'          => 'Verify',

        'otp_title'        => 'Verify Account | Astral Cloud',
        'otp_heading'      => 'Verify Your Email',
        'otp_sent_to'      => 'A verification code has been sent to',
        'otp_btn'          => 'Verify Account',

        // Product detail
        'prod_back'        => '← Back to Plans',
        'prod_in_stock'    => 'In stock',
        'prod_available'   => 'available',
        'prod_out_of_stock'=>'Out of stock',
        'prod_add_cart'    => 'Add to Cart',
        'prod_reviews'     => 'Customer Reviews',
        'prod_no_reviews'  => 'No reviews yet. Be the first to review this product!',

        // Blog
        'blog_title'       => 'Cloud Knowledge',
        'blog_card1_title' => 'What is VPS?',
        'blog_card1_desc'  => 'Learn how virtual private servers work in a cloud environment.',
        'blog_card2_title' => 'Choosing the Right VPS Plan',
        'blog_card2_desc'  => 'Understand how RAM, CPU, SSD and bandwidth affect performance.',
        'blog_card3_title' => 'Server Security Guide',
        'blog_card3_desc'  => 'Basic practices to keep your VPS safer and more reliable.',
        'blog_read_more'   => 'Read More →',

        // General
        'lang_switch'      => 'Tiếng Việt',
        'footer_tagline'   => 'High-performance VPS hosting for students, developers, and businesses. Deploy your server in minutes.',
        'footer_platform'  => 'Platform',
        'footer_account'   => 'Account',
        'footer_support'   => 'Support',
        'footer_copyright' => 'Astral Cloud. All rights reserved.',
        'footer_powered'   => 'Powered by PHP + MySQL + VMware',

        // Docs quick
        'docs_faq'         => 'FAQ',
        'docs_started'     => 'Getting Started',
        'docs_commands'    => 'Linux Commands',

        // Docs page
        'docs_heading'     => 'Documentation',
        'docs_subtitle'    => 'Everything you need to get started with your Astral Cloud VPS.',
        'docs_connect'     => 'Connecting to Your VPS',
        'docs_connect_p1'  => 'After purchasing a VPS plan, you can connect to it in two ways:',
        'docs_connect_h3a' => '1. Web Terminal (Browser)',
        'docs_connect_p2'  => 'The fastest way — no software needed. Go to My Orders and click the Console button next to your service.',
        'docs_connect_h3b' => '2. SSH Client',
        'docs_connect_p3'  => 'For advanced users, connect via any SSH client:',
        'docs_connect_p4'  => 'You can find your server IP and root password in My Orders → your service details.',
        'docs_terminal'    => 'Using the Web Terminal',
        'docs_terminal_p1' => 'The web terminal is a full-featured SSH console that runs in your browser.',
        'docs_terminal_li1'=> 'Resize: Drag the terminal window — it auto-adjusts.',
        'docs_terminal_li2'=> 'Copy/Paste: Right-click or use Ctrl+Shift+C / Ctrl+Shift+V.',
        'docs_terminal_li3'=> 'Reconnect: If the connection drops, it reconnects automatically.',
        'docs_terminal_li4'=> 'Multiple sessions: Open multiple browser tabs for multiple VPS instances.',
        'docs_manage'      => 'Managing Your VPS',
        'docs_manage_p1'   => 'From My Orders, you can control your VPS with these actions:',
        'docs_manage_start'=> 'Boot the VPS if stopped.',
        'docs_manage_stop' => 'Gracefully shut down. Your data is preserved.',
        'docs_manage_restart'=> 'Reset the VPS — useful when applying system updates.',
        'docs_manage_rebuild'=> 'Wipe the VPS and reinstall. All data will be lost.',
        'docs_commands_p1' => 'If you are new to Linux, here are the most useful commands:',
        'docs_webserver'   => 'Installing a Web Server',
        'docs_webserver_p1'=> 'Your VPS ships with Ubuntu. To host a website, install Apache or Nginx.',
        'docs_firewall'    => 'Basic Firewall Setup',
        'docs_firewall_p1' => 'Secure your VPS by allowing only necessary ports:',
        'docs_firewall_p2' => 'Always keep port 22 open, or you will lock yourself out!',
        'docs_faq_title'   => 'FAQ',
        'docs_faq_q1'      => 'Can I change my root password?',
        'docs_faq_a1'      => 'Yes. Connect via SSH and run: passwd',
        'docs_faq_q2'      => 'How long does provisioning take?',
        'docs_faq_a2'      => 'Usually 1-3 minutes. The VM is cloned and booted automatically after payment.',
        'docs_faq_q3'      => 'Can I install any OS?',
        'docs_faq_a3'      => 'Your VPS comes with Ubuntu 22.04 LTS. You can install other distributions manually.',
        'docs_faq_q4'      => 'What if I mess up my server?',
        'docs_faq_a4'      => 'Use the Rebuild button in My Orders. It resets to a fresh Ubuntu installation.',
        'docs_faq_q5'      => 'How do I cancel my service?',
        'docs_faq_a5'      => 'Go to My Orders, find your order, and click Cancel.',
        // Cart page
        'cart_title'       => 'Shopping Cart',
        'cart_empty'       => 'Cart is empty',
        'cart_empty_sub'   => 'Select a VPS package to get started.',
        'cart_browse'      => 'Browse VPS Plans',
        'cart_summary'     => 'Order Summary',
        'cart_estimated'   => 'Estimated price:',
        'cart_vat'         => 'VAT (0%):',
        'cart_total'       => 'Total:',
        'cart_checkout'    => 'Proceed to Checkout',
        // Inbox page
        'inbox_title'      => 'Inbox',
        'inbox_empty'      => 'No messages yet',
        'inbox_empty_sub'  => 'You will receive notifications and announcements here.',
        'inbox_back'       => 'Back to Home',
        'inbox_read'       => 'Mark read',
        'inbox_system'     => 'System',
        'inbox_admin'      => 'Admin',
        'inbox_new'        => 'NEW',
        'inbox_read_tag'   => 'READ',
        'inbox_view'       => 'View',
        'inbox_from'       => 'From',
        // Review modal
        'review_write'     => 'Write a Review',
        'review_rating'    => 'Rating',
        'review_comment'   => 'Your Review',
        'review_placeholder'=> 'Share your experience... (min 10 characters)',
        'review_submit'    => 'Submit Review',
        'review_cancel'    => 'Cancel',
        // Success page
        'success_confirmed'=> 'Order Confirmed!',
        'success_p1'       => 'Your payment was successful and your VPS is now being provisioned.',
        'success_what_next'=> 'What happens next?',
        'success_step1'    => 'Payment confirmed',
        'success_step1d'   => 'Your payment has been processed securely.',
        'success_step2'    => 'VPS provisioning',
        'success_step2d'   => 'Your virtual server is being created. This takes 1–3 minutes.',
        'success_step3'    => 'Access your VPS',
        'success_step3d'   => 'Your IP and password will appear in My Orders once ready.',
        'success_goto'     => 'Go to My Orders →',
        'success_help'     => 'Need help? Read our documentation →',
        // Orders page
        'orders_title'     => 'Your Services',
        'orders_back'      => '← Back to Home',
        'orders_empty'     => 'You have no active services yet',
        'orders_empty_sub' => 'Choose a VPS plan to get started.',
        'orders_create'    => 'Create a VPS now',
        'orders_invoice'   => 'Invoice',
        'orders_console'   => '▶ Console',
        'orders_cancel'    => '✕ Cancel',
        'orders_waiting'   => 'Waiting...',
        'orders_stop'      => '⏹ Stop',
        'orders_restart'   => '↻ Restart',
        'orders_start'     => '▶ Start',
        'orders_rebuild'   => '⚠ Rebuild',
        'orders_ip'        => 'IP Address:',
        'orders_os'        => 'OS:',
        'orders_password'  => 'Root Password:',
        'orders_expires'   => 'Expires:',
        'orders_resource'  => 'Resource Usage',
        'orders_cpu'       => 'CPU Load',
        'orders_ram'       => 'RAM',
        'orders_disk'      => 'Disk',
        'orders_updated'   => 'Updated',
        'orders_provisioning'=> 'Provisioning in progress',
        'orders_queued'    => 'Queued',
        'orders_creating'  => 'Creating VM',
        'orders_booting'   => 'Booting OS',
        'orders_waiting_ip'=> 'Waiting for network',
        'orders_preparing' => 'Setting up console',
        'orders_auto'      => 'This completes automatically. Please refresh in a moment.',
        'orders_assigning' => 'Assigning...',
        'orders_show'      => 'Show',
        'orders_hide'      => 'Hide',
    ],
    'vi' => [
        // Navbar
        'nav_home'         => 'TRANG CHỦ',
        'nav_features'     => 'TÍNH NĂNG',
        'nav_plans'        => 'GÓI VPS',
        'nav_docs'         => 'HƯỚNG DẪN',
        'nav_blog'         => 'BLOG',
        'nav_login'        => 'Đăng nhập',
        'nav_register'     => 'Bắt đầu ngay',
        'nav_inbox'        => 'Hộp thư',
        'nav_profile'      => 'Hồ sơ',
        'nav_orders'       => 'Đơn hàng',
        'nav_logout'       => 'Đăng xuất',
        'nav_cart'         => 'Giỏ hàng',
        'nav_admin'        => 'Quản trị',

        // Hero
        'hero_title1'      => 'Cloud VPS giúp dự án của bạn',
        'hero_title2'      => 'NHANH HƠN!',
        'hero_sub'         => 'Astral Cloud cung cấp VPS hiệu suất cao, triển khai nhanh, bảo mật ổn định và dễ dàng quản lý cho sinh viên, lập trình viên và doanh nghiệp.',
        'hero_btn_plans'   => 'Xem gói VPS',
        'hero_btn_start'   => 'Bắt đầu',

        // About
        'about_title'      => 'Tại sao chọn Astral Cloud?',
        'about_desc'       => 'Chúng tôi mô phỏng hệ thống cho thuê và quản lý VPS hiện đại, giúp người dùng tìm gói máy chủ, đặt hàng, thanh toán demo và theo dõi trạng thái kích hoạt.',
        'about_uptime'     => 'Thời gian hoạt động',
        'about_uptime_desc'=> 'Hạ tầng luôn sẵn sàng cho hiệu suất VPS ổn định.',
        'about_storage'    => 'Ổ cứng SSD',
        'about_storage_desc'=>'Lưu trữ siêu nhanh cho website, API và ứng dụng.',
        'about_support'    => 'Hỗ trợ',
        'about_support_desc'=>'Hỗ trợ chuyên nghiệp bất cứ khi nào bạn cần.',
        'about_ddos'       => 'Bảo vệ',
        'about_ddos_desc'  => 'Bảo vệ nâng cao chống lại các cuộc tấn công độc hại.',

        // Plans page
        'plans_title'      => 'Các gói VPS',
        'plans_sub'        => 'Các gói VPS phổ biến cho nhiều nhu cầu sử dụng.',
        'plans_all_title'  => 'Tất cả gói VPS',
        'plans_all_sub'    => 'Chọn gói VPS phù hợp với nhu cầu của bạn.',
        'plans_search'     => 'Tìm kiếm gói...',
        'plans_sort_price_asc'=> 'Giá: Thấp → Cao',
        'plans_sort_price_desc'=>'Giá: Cao → Thấp',
        'plans_sort_rating'=> 'Đánh giá cao nhất',
        'plans_sort_name'  => 'Tên: A → Z',
        'plans_search_btn' => 'Tìm',
        'plans_clear'      => 'Xóa',
        'plans_no_results' => 'Không tìm thấy gói VPS phù hợp.',
        'plans_results_for'=> 'Kết quả cho',
        'plans_found'      => 'sản phẩm được tìm thấy',
        'plans_month'      => '/tháng',
        'plans_reviews'    => 'Đánh giá',
        'plans_no_reviews' => 'Chưa có đánh giá',
        'plans_add_cart'   => 'Thêm vào giỏ',
        'plans_out_of_stock'=>'Hết hàng',
        'plans_view'       => 'Xem gói',
        'plans_cpu'        => 'CPU',
        'plans_ram'        => 'RAM',
        'plans_storage'    => 'Lưu trữ',
        'plans_bandwidth'  => 'Băng thông',

        // Auth
        'login_title'      => 'Đăng nhập | Astral Cloud',
        'login_heading'    => 'Đăng nhập',
        'login_email'      => 'Email',
        'login_password'   => 'Mật khẩu',
        'login_btn'        => 'Đăng nhập',
        'login_no_account' => 'Chưa có tài khoản?',
        'login_forgot'     => 'Quên mật khẩu?',
        'login_register'   => 'Đăng ký',

        'register_title'   => 'Đăng ký | Astral Cloud',
        'register_heading' => 'Tạo tài khoản',
        'register_name'    => 'Họ và tên',
        'register_phone'   => 'Số điện thoại (tùy chọn)',
        'register_confirm' => 'Xác nhận mật khẩu',
        'register_btn'     => 'Tạo tài khoản',
        'register_have_account' => 'Đã có tài khoản?',

        'mfa_title'        => 'Xác thực 2 lớp | Astral Cloud',
        'mfa_heading'      => 'Xác thực hai yếu tố',
        'mfa_sub'          => 'Nhập mã 6 chữ số từ ứng dụng xác thực của bạn.',
        'mfa_btn'          => 'Xác nhận',

        'otp_title'        => 'Xác thực tài khoản | Astral Cloud',
        'otp_heading'      => 'Xác thực Email',
        'otp_sent_to'      => 'Mã xác thực đã được gửi đến',
        'otp_btn'          => 'Xác thực tài khoản',

        // Product detail
        'prod_back'        => '← Quay lại gói VPS',
        'prod_in_stock'    => 'Còn hàng',
        'prod_available'   => 'có sẵn',
        'prod_out_of_stock'=>'Hết hàng',
        'prod_add_cart'    => 'Thêm vào giỏ',
        'prod_reviews'     => 'Đánh giá khách hàng',
        'prod_no_reviews'  => 'Chưa có đánh giá nào. Hãy là người đầu tiên đánh giá!',

        // Blog
        'blog_title'       => 'Kiến thức Cloud',
        'blog_card1_title' => 'VPS là gì?',
        'blog_card1_desc'  => 'Tìm hiểu cách máy chủ ảo hoạt động trong môi trường đám mây.',
        'blog_card2_title' => 'Chọn gói VPS phù hợp',
        'blog_card2_desc'  => 'Hiểu RAM, CPU, SSD và băng thông ảnh hưởng đến hiệu suất.',
        'blog_card3_title' => 'Hướng dẫn bảo mật máy chủ',
        'blog_card3_desc'  => 'Các biện pháp cơ bản giúp VPS an toàn và đáng tin cậy hơn.',
        'blog_read_more'   => 'Đọc thêm →',

        // General
        'lang_switch'      => 'English',
        'footer_tagline'   => 'Dịch vụ VPS hiệu suất cao cho sinh viên, lập trình viên và doanh nghiệp. Triển khai máy chủ trong vài phút.',
        'footer_platform'  => 'Nền tảng',
        'footer_account'   => 'Tài khoản',
        'footer_support'   => 'Hỗ trợ',
        'footer_copyright' => 'Astral Cloud. Đã đăng ký bản quyền.',
        'footer_powered'   => 'Xây dựng bởi PHP + MySQL + VMware',

        // Docs quick
        'docs_faq'         => 'Câu hỏi thường gặp',
        'docs_started'     => 'Bắt đầu',
        'docs_commands'    => 'Lệnh Linux',

        // Docs page
        'docs_heading'     => 'Hướng dẫn',
        'docs_subtitle'    => 'Mọi thứ bạn cần để bắt đầu với VPS Astral Cloud.',
        'docs_connect'     => 'Kết nối đến VPS của bạn',
        'docs_connect_p1'  => 'Sau khi mua gói VPS, bạn có thể kết nối bằng hai cách:',
        'docs_connect_h3a' => '1. Web Terminal (Trình duyệt)',
        'docs_connect_p2'  => 'Cách nhanh nhất — không cần phần mềm. Vào Đơn hàng và nhấp nút Console.',
        'docs_connect_h3b' => '2. SSH Client',
        'docs_connect_p3'  => 'Dành cho người dùng nâng cao, kết nối qua SSH client:',
        'docs_connect_p4'  => 'Bạn có thể tìm IP và mật khẩu root trong Đơn hàng → chi tiết dịch vụ.',
        'docs_terminal'    => 'Sử dụng Web Terminal',
        'docs_terminal_p1' => 'Web terminal là bảng điều khiển SSH đầy đủ chạy trong trình duyệt.',
        'docs_terminal_li1'=> 'Thay đổi kích thước: Kéo cửa sổ terminal — tự động điều chỉnh.',
        'docs_terminal_li2'=> 'Sao chép/Dán: Nhấp chuột phải hoặc dùng Ctrl+Shift+C / Ctrl+Shift+V.',
        'docs_terminal_li3'=> 'Kết nối lại: Nếu mất kết nối, tự động kết nối lại.',
        'docs_terminal_li4'=> 'Nhiều phiên: Mở nhiều tab cho nhiều VPS.',
        'docs_manage'      => 'Quản lý VPS',
        'docs_manage_p1'   => 'Từ Đơn hàng, bạn có thể điều khiển VPS với các hành động:',
        'docs_manage_start'=> 'Khởi động VPS nếu đã dừng.',
        'docs_manage_stop' => 'Tắt an toàn. Dữ liệu được bảo toàn.',
        'docs_manage_restart'=> 'Khởi động lại VPS — hữu ích khi cập nhật hệ thống.',
        'docs_manage_rebuild'=> 'Xóa VPS và cài lại. Tất cả dữ liệu sẽ bị mất.',
        'docs_commands_p1' => 'Nếu bạn mới dùng Linux, đây là các lệnh hữu ích nhất:',
        'docs_webserver'   => 'Cài đặt Web Server',
        'docs_webserver_p1'=> 'VPS của bạn chạy Ubuntu. Để lưu trữ website, cài Apache hoặc Nginx.',
        'docs_firewall'    => 'Thiết lập tường lửa cơ bản',
        'docs_firewall_p1' => 'Bảo vệ VPS bằng cách chỉ cho phép các cổng cần thiết:',
        'docs_firewall_p2' => 'Luôn giữ cổng 22 mở, nếu không bạn sẽ bị khóa!',
        'docs_faq_title'   => 'Câu hỏi thường gặp',
        'docs_faq_q1'      => 'Tôi có thể đổi mật khẩu root không?',
        'docs_faq_a1'      => 'Có. Kết nối qua SSH và chạy: passwd',
        'docs_faq_q2'      => 'Quá trình provisioning mất bao lâu?',
        'docs_faq_a2'      => 'Thường 1-3 phút. VM được sao chép và khởi động tự động sau khi thanh toán.',
        'docs_faq_q3'      => 'Tôi có thể cài hệ điều hành khác không?',
        'docs_faq_a3'      => 'VPS của bạn chạy Ubuntu 22.04 LTS. Bạn có thể cài bản phân phối khác thủ công.',
        'docs_faq_q4'      => 'Nếu tôi làm hỏng máy chủ thì sao?',
        'docs_faq_a4'      => 'Dùng nút Rebuild trong Đơn hàng. Nó đặt lại về Ubuntu mới.',
        'docs_faq_q5'      => 'Làm sao để hủy dịch vụ?',
        'docs_faq_a5'      => 'Vào Đơn hàng, tìm đơn và nhấp Hủy.',
        // Cart page
        'cart_title'       => 'Giỏ hàng',
        'cart_empty'       => 'Giỏ hàng trống',
        'cart_empty_sub'   => 'Chọn gói VPS để bắt đầu.',
        'cart_browse'      => 'Xem gói VPS',
        'cart_summary'     => 'Tóm tắt đơn hàng',
        'cart_estimated'   => 'Giá ước tính:',
        'cart_vat'         => 'VAT (0%):',
        'cart_total'       => 'Tổng cộng:',
        'cart_checkout'    => 'Tiến hành thanh toán',
        // Inbox page
        'inbox_title'      => 'Hộp thư',
        'inbox_empty'      => 'Chưa có tin nhắn',
        'inbox_empty_sub'  => 'Bạn sẽ nhận thông báo và tin tức tại đây.',
        'inbox_back'       => 'Về trang chủ',
        'inbox_read'       => 'Đánh dấu đã đọc',
        'inbox_system'     => 'Hệ thống',
        'inbox_admin'      => 'Quản trị',
        'inbox_new'        => 'MỚI',
        'inbox_read_tag'   => 'ĐÃ ĐỌC',
        'inbox_view'       => 'Xem',
        'inbox_from'       => 'Từ',
        // Review modal
        'review_write'     => 'Viết đánh giá',
        'review_rating'    => 'Xếp hạng',
        'review_comment'   => 'Đánh giá của bạn',
        'review_placeholder'=> 'Chia sẻ trải nghiệm... (tối thiểu 10 ký tự)',
        'review_submit'    => 'Gửi đánh giá',
        'review_cancel'    => 'Hủy',
        // Success page
        'success_confirmed'=> 'Đặt hàng thành công!',
        'success_p1'       => 'Thanh toán thành công và VPS của bạn đang được tạo.',
        'success_what_next'=> 'Tiếp theo là gì?',
        'success_step1'    => 'Thanh toán đã xác nhận',
        'success_step1d'   => 'Thanh toán của bạn đã được xử lý an toàn.',
        'success_step2'    => 'Đang tạo VPS',
        'success_step2d'   => 'Máy chủ ảo đang được tạo. Quá trình mất 1–3 phút.',
        'success_step3'    => 'Truy cập VPS',
        'success_step3d'   => 'IP và mật khẩu sẽ xuất hiện trong Đơn hàng khi sẵn sàng.',
        'success_goto'     => 'Đến Đơn hàng →',
        'success_help'     => 'Cần trợ giúp? Đọc hướng dẫn →',
        // Orders page
        'orders_title'     => 'Dịch vụ của bạn',
        'orders_back'      => '← Về trang chủ',
        'orders_empty'     => 'Bạn chưa có dịch vụ nào',
        'orders_empty_sub' => 'Chọn gói VPS để bắt đầu.',
        'orders_create'    => 'Tạo VPS ngay',
        'orders_invoice'   => 'Hóa đơn',
        'orders_console'   => '▶ Console',
        'orders_cancel'    => '✕ Hủy',
        'orders_waiting'   => 'Đang chờ...',
        'orders_stop'      => '⏹ Dừng',
        'orders_restart'   => '↻ Khởi động lại',
        'orders_start'     => '▶ Bắt đầu',
        'orders_rebuild'   => '⚠ Cài lại',
        'orders_ip'        => 'Địa chỉ IP:',
        'orders_os'        => 'HĐH:',
        'orders_password'  => 'Mật khẩu Root:',
        'orders_expires'   => 'Hết hạn:',
        'orders_resource'  => 'Sử dụng tài nguyên',
        'orders_cpu'       => 'CPU',
        'orders_ram'       => 'RAM',
        'orders_disk'      => 'Ổ đĩa',
        'orders_updated'   => 'Cập nhật',
        'orders_provisioning'=> 'Đang khởi tạo',
        'orders_queued'    => 'Đang chờ',
        'orders_creating'  => 'Đang tạo VM',
        'orders_booting'   => 'Đang khởi động',
        'orders_waiting_ip'=> 'Đợi mạng',
        'orders_preparing' => 'Thiết lập console',
        'orders_auto'      => 'Hoàn tất tự động. Vui lòng tải lại trang sau ít phút.',
        'orders_assigning' => 'Đang gán...',
        'orders_show'      => 'Hiện',
        'orders_hide'      => 'Ẩn',
    ]
];

// Translation helper — use in views: __( 'nav_home' )
function __(string $key): string {
    global $lang, $langData;
    return $langData[$lang][$key] ?? $langData['en'][$key] ?? $key;
}
